version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data:ro
    # depends_on:
    #   - streamlit
    restart: always

  # streamlit:
  #   image: streamlit:latest
  #   container_name: streamlit-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile # 如果有自定义 Dockerfile
  #   ports:
  #     - "8501:8501"
  #   restart: always
